/**
 * Auto-generated types for Supabase database schema
 * 
 * This file defines the complete TypeScript representation of the PermitPilot
 * Supabase database schema, including all tables with Row, Insert, and Update types.
 */

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          company_type: string | null;
          logo_url: string | null;
          primary_jurisdiction: string | null;
          active_nc_jurisdictions: string[];
          settings: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          company_type?: string | null;
          logo_url?: string | null;
          primary_jurisdiction?: string | null;
          active_nc_jurisdictions?: string[];
          settings?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          company_type?: string | null;
          logo_url?: string | null;
          primary_jurisdiction?: string | null;
          active_nc_jurisdictions?: string[];
          settings?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          organization_id: string | null;
          full_name: string;
          email: string;
          avatar_url: string | null;
          role: 'owner' | 'admin' | 'member' | 'viewer';
          job_title: string | null;
          phone: string | null;
          notification_preferences: Record<string, unknown>;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          full_name: string;
          email: string;
          avatar_url?: string | null;
          role?: 'owner' | 'admin' | 'member' | 'viewer';
          job_title?: string | null;
          phone?: string | null;
          notification_preferences?: Record<string, unknown>;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          full_name?: string;
          email?: string;
          avatar_url?: string | null;
          role?: 'owner' | 'admin' | 'member' | 'viewer';
          job_title?: string | null;
          phone?: string | null;
          notification_preferences?: Record<string, unknown>;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          organization_id: string;
          project_number: string;
          name: string;
          description: string | null;
          address: string | null;
          city: string | null;
          county: string | null;
          jurisdiction: string;
          project_type: 'residential' | 'commercial' | 'mixed_use' | 'industrial' | 'institutional' | 'infrastructure' | null;
          status: 'draft' | 'active' | 'on_hold' | 'completed' | 'archived';
          lead_id: string | null;
          acreage: number | null;
          parcel_ids: string[];
          zoning_district: string | null;
          estimated_value: number | null;
          target_completion_date: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          project_number: string;
          name: string;
          description?: string | null;
          address?: string | null;
          city?: string | null;
          county?: string | null;
          jurisdiction: string;
          project_type?: 'residential' | 'commercial' | 'mixed_use' | 'industrial' | 'institutional' | 'infrastructure' | null;
          status?: 'draft' | 'active' | 'on_hold' | 'completed' | 'archived';
          lead_id?: string | null;
          acreage?: number | null;
          parcel_ids?: string[];
          zoning_district?: string | null;
          estimated_value?: number | null;
          target_completion_date?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          project_number?: string;
          name?: string;
          description?: string | null;
          address?: string | null;
          city?: string | null;
          county?: string | null;
          jurisdiction?: string;
          project_type?: 'residential' | 'commercial' | 'mixed_use' | 'industrial' | 'institutional' | 'infrastructure' | null;
          status?: 'draft' | 'active' | 'on_hold' | 'completed' | 'archived';
          lead_id?: string | null;
          acreage?: number | null;
          parcel_ids?: string[];
          zoning_district?: string | null;
          estimated_value?: number | null;
          target_completion_date?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
      };
      permits: {
        Row: {
          id: string;
          project_id: string;
          organization_id: string;
          permit_number: string;
          permit_type: 'site_plan_review' | 'building_permit' | 'zoning_variance' | 'stormwater_review' | 'grading_permit' | 'demolition_permit' | 'sign_permit' | 'special_use_permit' | 'subdivision_review' | 'other';
          title: string;
          description: string | null;
          jurisdiction: string;
          status: 'draft' | 'submitted' | 'under_review' | 'revision_requested' | 'resubmitted' | 'approved' | 'approved_with_conditions' | 'denied' | 'withdrawn' | 'expired';
          priority: 'low' | 'normal' | 'high' | 'urgent';
          assigned_reviewer: string | null;
          reviewer_email: string | null;
          submitted_at: string | null;
          decision_date: string | null;
          expiration_date: string | null;
          fee_amount: number | null;
          fee_paid: boolean;
          jurisdiction_portal_url: string | null;
          jurisdiction_reference_number: string | null;
          metadata: Record<string, unknown>;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          organization_id: string;
          permit_number: string;
          permit_type: 'site_plan_review' | 'building_permit' | 'zoning_variance' | 'stormwater_review' | 'grading_permit' | 'demolition_permit' | 'sign_permit' | 'special_use_permit' | 'subdivision_review' | 'other';
          title: string;
          description?: string | null;
          jurisdiction: string;
          status?: 'draft' | 'submitted' | 'under_review' | 'revision_requested' | 'resubmitted' | 'approved' | 'approved_with_conditions' | 'denied' | 'withdrawn' | 'expired';
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          assigned_reviewer?: string | null;
          reviewer_email?: string | null;
          submitted_at?: string | null;
          decision_date?: string | null;
          expiration_date?: string | null;
          fee_amount?: number | null;
          fee_paid?: boolean;
          jurisdiction_portal_url?: string | null;
          jurisdiction_reference_number?: string | null;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          organization_id?: string;
          permit_number?: string;
          permit_type?: 'site_plan_review' | 'building_permit' | 'zoning_variance' | 'stormwater_review' | 'grading_permit' | 'demolition_permit' | 'sign_permit' | 'special_use_permit' | 'subdivision_review' | 'other';
          title?: string;
          description?: string | null;
          jurisdiction?: string;
          status?: 'draft' | 'submitted' | 'under_review' | 'revision_requested' | 'resubmitted' | 'approved' | 'approved_with_conditions' | 'denied' | 'withdrawn' | 'expired';
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          assigned_reviewer?: string | null;
          reviewer_email?: string | null;
          submitted_at?: string | null;
          decision_date?: string | null;
          expiration_date?: string | null;
          fee_amount?: number | null;
          fee_paid?: boolean;
          jurisdiction_portal_url?: string | null;
          jurisdiction_reference_number?: string | null;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      permit_status_history: {
        Row: {
          id: string;
          permit_id: string;
          from_status: string | null;
          to_status: string;
          changed_by: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          permit_id: string;
          from_status?: string | null;
          to_status: string;
          changed_by?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          permit_id?: string;
          from_status?: string | null;
          to_status?: string;
          changed_by?: string | null;
          note?: string | null;
          created_at?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          permit_id: string;
          organization_id: string;
          author_id: string | null;
          author_name: string;
          author_role: string | null;
          source: 'internal' | 'jurisdiction' | 'imported';
          category: 'parking_access' | 'stormwater' | 'building_code' | 'zoning' | 'fire_safety' | 'landscaping' | 'traffic' | 'environmental' | 'general' | 'other' | null;
          body: string;
          is_resolved: boolean;
          resolved_by: string | null;
          resolved_at: string | null;
          parent_comment_id: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          permit_id: string;
          organization_id: string;
          author_id?: string | null;
          author_name: string;
          author_role?: string | null;
          source: 'internal' | 'jurisdiction' | 'imported';
          category?: 'parking_access' | 'stormwater' | 'building_code' | 'zoning' | 'fire_safety' | 'landscaping' | 'traffic' | 'environmental' | 'general' | 'other' | null;
          body: string;
          is_resolved?: boolean;
          resolved_by?: string | null;
          resolved_at?: string | null;
          parent_comment_id?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          permit_id?: string;
          organization_id?: string;
          author_id?: string | null;
          author_name?: string;
          author_role?: string | null;
          source?: 'internal' | 'jurisdiction' | 'imported';
          category?: 'parking_access' | 'stormwater' | 'building_code' | 'zoning' | 'fire_safety' | 'landscaping' | 'traffic' | 'environmental' | 'general' | 'other' | null;
          body?: string;
          is_resolved?: boolean;
          resolved_by?: string | null;
          resolved_at?: string | null;
          parent_comment_id?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
      };
      documents: {
        Row: {
          id: string;
          organization_id: string;
          project_id: string | null;
          permit_id: string | null;
          comment_id: string | null;
          uploaded_by: string | null;
          file_name: string;
          file_type: string | null;
          file_size: number | null;
          storage_path: string;
          document_type: 'site_plan' | 'architectural_drawing' | 'civil_drawing' | 'survey' | 'environmental_report' | 'traffic_study' | 'stormwater_plan' | 'photo' | 'correspondence' | 'approval_letter' | 'rejection_letter' | 'other' | null;
          version: number;
          description: string | null;
          is_public: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          project_id?: string | null;
          permit_id?: string | null;
          comment_id?: string | null;
          uploaded_by?: string | null;
          file_name: string;
          file_type?: string | null;
          file_size?: number | null;
          storage_path: string;
          document_type?: 'site_plan' | 'architectural_drawing' | 'civil_drawing' | 'survey' | 'environmental_report' | 'traffic_study' | 'stormwater_plan' | 'photo' | 'correspondence' | 'approval_letter' | 'rejection_letter' | 'other' | null;
          version?: number;
          description?: string | null;
          is_public?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          project_id?: string | null;
          permit_id?: string | null;
          comment_id?: string | null;
          uploaded_by?: string | null;
          file_name?: string;
          file_type?: string | null;
          file_size?: number | null;
          storage_path?: string;
          document_type?: 'site_plan' | 'architectural_drawing' | 'civil_drawing' | 'survey' | 'environmental_report' | 'traffic_study' | 'stormwater_plan' | 'photo' | 'correspondence' | 'approval_letter' | 'rejection_letter' | 'other' | null;
          version?: number;
          description?: string | null;
          is_public?: boolean;
          created_at?: string;
        };
      };
      activity_log: {
        Row: {
          id: string;
          organization_id: string;
          project_id: string | null;
          permit_id: string | null;
          actor_id: string | null;
          action: 'project_created' | 'permit_submitted' | 'comment_added' | 'status_changed' | 'document_uploaded' | 'reviewer_assigned' | 'deadline_set' | 'permit_approved' | 'permit_denied' | 'resubmittal_required';
          description: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          project_id?: string | null;
          permit_id?: string | null;
          actor_id?: string | null;
          action: 'project_created' | 'permit_submitted' | 'comment_added' | 'status_changed' | 'document_uploaded' | 'reviewer_assigned' | 'deadline_set' | 'permit_approved' | 'permit_denied' | 'resubmittal_required';
          description?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          project_id?: string | null;
          permit_id?: string | null;
          actor_id?: string | null;
          action?: 'project_created' | 'permit_submitted' | 'comment_added' | 'status_changed' | 'document_uploaded' | 'reviewer_assigned' | 'deadline_set' | 'permit_approved' | 'permit_denied' | 'resubmittal_required';
          description?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
        };
      };
      deadlines: {
        Row: {
          id: string;
          organization_id: string;
          project_id: string | null;
          permit_id: string | null;
          title: string;
          description: string | null;
          due_date: string;
          status: 'upcoming' | 'due_soon' | 'overdue' | 'completed' | 'cancelled';
          reminder_days_before: number[];
          assigned_to: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          project_id?: string | null;
          permit_id?: string | null;
          title: string;
          description?: string | null;
          due_date: string;
          status?: 'upcoming' | 'due_soon' | 'overdue' | 'completed' | 'cancelled';
          reminder_days_before?: number[];
          assigned_to?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          project_id?: string | null;
          permit_id?: string | null;
          title?: string;
          description?: string | null;
          due_date?: string;
          status?: 'upcoming' | 'due_soon' | 'overdue' | 'completed' | 'cancelled';
          reminder_days_before?: number[];
          assigned_to?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
      };
      jurisdictions: {
        Row: {
          id: string;
          name: string;
          state: string;
          county: string | null;
          portal_url: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          avg_review_days: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          state: string;
          county?: string | null;
          portal_url?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          avg_review_days?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          state?: string;
          county?: string | null;
          portal_url?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          avg_review_days?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      marketing_leads: {
        Row: {
          id: string;
          intent: string;
          full_name: string;
          email: string;
          company: string;
          company_type: string;
          source_path: string;
          active_nc_jurisdictions: string[];
          primary_nc_jurisdiction: string | null;
          annual_project_volume: string | null;
          biggest_workflow_issue: string | null;
          issue_category: string | null;
          note: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
        };
        Insert: {
          id?: string;
          intent: string;
          full_name: string;
          email: string;
          company: string;
          company_type: string;
          source_path: string;
          active_nc_jurisdictions: string[];
          primary_nc_jurisdiction?: string | null;
          annual_project_volume?: string | null;
          biggest_workflow_issue?: string | null;
          issue_category?: string | null;
          note?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
        };
        Update: {
          id?: string;
          intent?: string;
          full_name?: string;
          email?: string;
          company?: string;
          company_type?: string;
          source_path?: string;
          active_nc_jurisdictions?: string[];
          primary_nc_jurisdiction?: string | null;
          annual_project_volume?: string | null;
          biggest_workflow_issue?: string | null;
          issue_category?: string | null;
          note?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
        };
      };
    };
  };
};
